ks: 1
kd: 1
discontinuity_threshold: 0.3
radius_normal_estimation: 0.5
neighbor_search: 4

# Available options: none, custom, adaptive
limits: none
custom_depth_limit_min: 0
custom_depth_limit_max: 1

# Available options: none, nearest_neighbor, triangles, mean_depth
initialization: mean_depth

# Available options: four, eight
neighborhood: four

# Available options: trivial, huber
loss_function: trivial
loss_function_scale: 1

use_cost_functor_normal_distance: true
use_cost_functor_normal_smoothness: true
use_cost_functor_normal: true
use_cost_functor_depth: true
use_cost_functor_depth_smoothness: true
