# Distance weight
kd: 1

# Smoothness weight (within discontinuity threshold)
ks: 1

# Normal distance weight
kn: 1

# Threshold at which smoothness weighting starts to decrease
discontinuity_threshold: 0.1

# Exponential decrease rate of smoothness weighting
smoothness_rate: 25
smoothness_weight_min: 0.0001

# Whether normal estimation is performed as a preprocessing step
# This parameter can be set to false if normals are not needed or provided
# otherwise
estimate_normals: true

# Radius in which the normal estimation is performed
radius_normal_estimation: 0.3

# Number of neighbors to search for during initialization
neighbor_search: 20

# Depth limits that constrain the optimization
# Available options: none, custom, adaptive
limits: adaptive
custom_depth_limit_min: 0
custom_depth_limit_max: 1

# Available options: none, nearest_neighbor, triangles, mean_depth
initialization: mean_depth

# Neighborhood for each pixel to consider
# Available options: two, four, eight
neighborhood: eight

# Optimizer parameters
# Available options: trivial, huber, cauchy
loss_function: trivial
loss_function_scale: 0.1
max_num_iterations: 500
minimizer_progress_to_stdout: true
num_threads: 8
num_linear_solver_threads: 8
max_solver_time_in_seconds: 1200
use_inner_iterations: true
use_nonmonotonic_steps: false

use_functor_distance: true
use_functor_normal: false
use_functor_normal_distance: false
use_functor_smoothness_normal: false
use_functor_smoothness_distance: true

pin_normals: true
pin_distances: true

estimate_covariances: false
