# Distance weight
kd: 1

# Smoothness weight (within discontinuity threshold)
ks: 1

# Normal weight
kn: 1

# Threshold at which smoothness weighting starts to decrease
discontinuity_threshold: 0.1

# Exponential decrease rate of smoothness weighting
smoothness_rate: 50

# Whether normal estimation is performed as a preprocessing step
# This parameter can be set to false if normals are not needed or provided
# otherwise
estimate_normals: true

# Radius in which the normal estimation is performed
radius_normal_estimation: 0.4

# Number of neighbors to search for during initialization
neighbor_search: 4

# Depth limits that constrain the optimization
# Available options: none, custom, adaptive
limits: none
custom_depth_limit_min: 0
custom_depth_limit_max: 1

# Available options: none, nearest_neighbor, triangles, mean_depth
initialization: mean_depth

# Neighborhood for each pixel to consider
# Available options: four, eight
neighborhood: eight

# Available options: trivial, huber
loss_function: trivial
loss_function_scale: 1
max_num_iterations: 50

use_functor_distance: true
use_functor_normal: true
use_functor_normal_distance: true
use_functor_smoothness_normal: true
use_functor_smoothness_distance: false

pin_normals: true
pin_distances: true

estimate_covariances: true
