kd: 1
ks: 100
kn: 1

discontinuity_threshold: 0.1
smoothness_rate: 100000
radius_normal_estimation: 0.5
neighbor_search: 4

# Available options: none, custom, adaptive
limits: none
custom_depth_limit_min: 0
custom_depth_limit_max: 1

# Available options: none, nearest_neighbor, triangles, mean_depth
initialization: none

# Available options: four, eight
neighborhood: eight

# Available options: trivial, huber
loss_function: trivial
loss_function_scale: 1

use_functor_distance: true
use_functor_normal: true
use_functor_normal_distance: true
use_functor_smoothness_normal: true
use_functor_smoothness_distance: true

pin_normals: true
pin_distances: true
